[package]
name = "finger"
version = "0.1.0"
authors = ["Chad Catlett <chad@catlett.info>"]
description = "Finger code with multiple backends"
license = "to be determined"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
