[package]
name = "finger"
version = "0.1.0"
authors = ["Chad Catlett <chad@catlett.info>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
